server:
  port: 18500

spring:
  application:
    name: uncrash-user-service
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/uncrash
    username: root
    password: ChangeMe!!!
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

uncrash:
  swagger2:
    enabled: true
    host: api.uncrash.net
    base-package: net.uncrash.web.controller
    title: Uncrash REST API
    description: Fast website and server uptime monitoring.
    version: v1
    tos-url: https://uncrash.net/tos
    contact-name: Uncrash
    contact-url: https://uncrash.net
    contact-email: contact@uncrash.net
    license: MIT
    licenseUrl: https://opensource.org/licenses/MIT