server:
  port: 18505

spring:
  application:
    name: uncrash-agent-service
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/uncrash
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://dev.uncrash.net:8761/eureka/

uncrash:
  swagger2:
    enabled: true
      host: https://api.uncrash.net
    base-package: net.uncrash.web.controller
    title: Uncrash REST API
    description: Fast website and server uptime monitoring.
    version: v1
    tos-url: https://uncrash.net/tos
    contact-name: Uncrash
    contact-url: https://uncrash.net
    contact-email: contact@uncrash.net
    license: MIT
    licenseUrl: https://opensource.org/licenses/MIT